# Generated by Django 2.0.7 on 2018-08-22 18:37

from django.db import migrations, models
import django.db.models.deletion
import emailapp.models
import emailapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('secondary', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterCategoryOpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_general', models.BooleanField(default=False)),
                ('opt_sales', models.BooleanField(default=False)),
                ('opt_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=None, max_length=254)),
                ('id_email', models.IntegerField(db_index=True, default=emailapp.models.id_increment, editable=False)),
                ('token', models.CharField(default=emailapp.utils.generate_token, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Proximity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=None, max_length=254)),
                ('city', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newslettercategoryopt',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailapp.NewsletterRecipient'),
        ),
    ]
