# Generated by Django 2.0.7 on 2018-09-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='firstname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletterrecipient',
            name='lastname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
