# Generated by Django 2.0.7 on 2018-07-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('secondary', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=None, db_index=True, max_length=254)),
                ('subs_at', models.DateField(auto_now_add=True)),
                ('opt_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proximity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=None, max_length=254)),
                ('city', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
