# Generated by Django 2.0.7 on 2018-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_auto_20180718_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id_address',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
